// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AttendanceMarkController from "./attendance_mark_controller"
application.register("attendance-mark", AttendanceMarkController)

import AutoFormatController from "./auto_format_controller"
application.register("auto-format", AutoFormatController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NoticeController from "./notice_controller"
application.register("notice", NoticeController)

import SearchController from "./search_controller"
application.register("search", SearchController)
